app/Http/routes.php
<?php

use App\Image;
use Illuminate\Http\Request;
use App\Role;
use App\User;
use App\Category;
use App\Album;

Route::auth();

/******************************    ADMIN   ******************************************/
Route::group(['middleware' => ['AdminMiddleware', 'auth']], function()
{		
		Route::get('/admin', 'HomeController@index');
		
		Route::resource('user', 'UserController');
		Route::resource('role','RoleController');
    Route::resource('category', 'CategoryController');
    Route::resource('album', 'AlbumController');

    Route::put('/remove/{album}', 'CategoryController@removeAlbum');
    Route::put('/removeimg/{image}', 'AlbumController@removeImage');

    Route::get('roles/{role}', 'RoleController@show');
    Route::get('roles', 'RoleController@index');
		Route::get('user/create', 'UserController@create');
    Route::post('user/store', 'UserController@store');
    
    // Route::post('reset_password', 'UserController@test_fn');
    // Route::get('/reset_password', 'UserController@test_fn');
});

/*******************************   AUTH USER  *********************************************/
Route::group(['middleware' => 'auth'], function () {

  // CART BEGIN
  Route::get('/paypal_success', [
    'uses' => 'ImageController@successPayPal',
    'as' => 'Image.successPayPal'
  ]);
  Route::get('/checkout', [
    'uses' => 'ImageController@getCheckout',
    'as' => 'checkout',
  ]);
  Route::post('/checkout', [
    'uses' => 'ImageController@postCheckout',
    'as' => 'checkout',
  ]);
  Route::get('/shopping_cart\/', [
    'uses' => 'ImageController@getShoppingCart',
    'as' => 'image.getShoppingCart'
    ]
  );
  Route::get('/add_to_cart/{image}', [
      'uses' => 'ImageController@addImageToCart',
      'as' => 'image.addImageToCart'
    ]
  );
  Route::get('/decrease/{id}', [
    'uses' => 'ImageController@getDecreaseQty',
    'as' => 'image.decreaseQty'
  ]);
  Route::get('/increase/{id}', [
    'uses' => 'ImageController@getIncreaseQty',
    'as' => 'image.increaseQty'
  ]); 
  Route::get('/remove/{id}', [
    'uses' => 'ImageController@getRemoveImage',
    'as' => 'image.removeImage'
  ]);
  
  // CART END

  Route::get('/category','CategoryController@index');
  Route::get('/category/{category}','CategoryController@show');

  Route::get('/album','AlbumController@index');
  Route::get('/album/{album}','AlbumController@show');

  Route::get('/', 'CategoryController@index');
  // Route::get('/reset_password', 'UserController@change_password');

  Route::resource('image', 'ImageController');

  Route::get('/home', 'CategoryController@index');

  Route::post('user', 'UserController@store');
  Route::post('reset_password', 'PasswordResetController@reset_submit');
  Route::get('/reset_password', 'PasswordResetController@reset_password');
});

app/Role.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;

class Role extends \Eloquent
{
	protected $fillable = ['name', 'description'];
 
    public function users()
    {
        return $this->hasMany('App\User');
    }
    public function addUser(User $user)
    {
   		return	$this->users()->save($user);
    }
    public function hasUsers()
    {
       return $this->users->count()> 0;
    }
    public function getUsers()
    {
      return  $this->users()->get();
    }
    
}

app/Http/Controllers/RoleController.php
<?php
namespace App\Http\Controllers;
use App\User;
use App\Role;
use Session;
use Auth;
use Hash;
use Illuminate\Support\MessageBag;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Input;
use App\Http\Requests;

class RoleController extends Controller
{
     public function index()
    {       
        $roles = Role::all();
        return view('admin.roles.index')->with('roles', $roles);
    }

     public function store(Request $request)
    {

        if ($request->isMethod('post')) {
              
            $r = new Role();
            //$note = new Note($req->all());
             $r->name= $request->input('name');
               $r->description= $request->input('description');
               $r->save();
               Session::flash('role_created','Role Created Successfully !');
               return response()->json(['success' => true]);

        }      
    }

    public function show(Role $role)
    {
      return view('admin.roles.show', compact('role') );
    }

    public function edit(Role $role)
    {
       return view('admin.roles.edit', compact('role'));
    }
    public function update(Request $request, Role $role)
    {
      //$roles = Role::all();
      if($request->description == $role->description && $request->name == $role->name){
        //$role->update($request->all());
      return redirect()->route('role.index');
      }
      else
      {
          $this->validate($request, [ 
       'name' =>  'required|min:4|max:32',   
      'description' => 'required|min:4|max:32',
            ]);
             
       $role->update($request->all());
       $role->save();
       Session::flash('role_updated', 'Successfully Updated');
       return redirect()->route('role.index');
      }
    
  }
    public function destroy(Role $role)
    {
          if(count($role->getUsers())==0)
          {
            $role->delete();
            Session::flash('role_deleted', 'Successfully Deleted');
            return redirect()->route('role.index');
          }
            else{
                $r = Role::find(2);
                foreach($role->getUsers() as $key=>$value ) {

                        $r->addUser($value);
                    
                }
                $role->delete();
                 return back()->with('change_role', 'USERS ASSIGNED THIS ROLE NOWHAVE  CLIENT ROLE ');

            }
    }
}

resources/views/admin/roles/create.blade.php
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">     
@include('errors')
                      @if (session('status'))
                               <div class="alert alert-success"> {{ session('status') }}</div>
                        
                      @endif
          <center><h2>Create New Role</h2></center>
          <p></p>
        {{ Form::open((array('url' => 'role/store', 'method' => 'get'))) }}
            {!! Form::label('name','Role Name: ') !!}
             {!! Form::text('name',null,  array(
                                        'class'=> 'form-control'
                                        )) !!}
            {!! Form::label('description','Role Description: ') !!}
             {!! Form::text('description',null, array(
                                        'class'=> 'form-control'
                                        )) !!}                                         
                                    <p></p>
                                    <p></p>
                                    <center>
               {!! Form::submit('Submit',array(
                                  'class'=> 'btn btn-primary'
                                        )) !!}  </center>
                       

         {!! Form::close() !!}

        </div>
    </div>
</div>

resources/views/admin/roles/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
@include('errors')
<p class="lead">Edit User</p>
<div class="row ">
<div class="col-xs-6">
		
	{!! Form::model($role, [  'method' => 'PUT',  'route' => ['role.update', $role->id]]) !!}
		{{csrf_field() }}
 
    <table class="table">
    
	  		<tr> 
	          <th>Name</th><td>{!! Form::text('name', null, ['class' => 'form-control'] ) !!}</td>     		
	        </tr>
	         <tr> 
	         <th>Description</th><td>{!! Form::text('description', null, ['class' => 'form-control']) !!}</td> 	
	        </tr>
			  
   
  </table>
  </div>
  	<div class="col-xs-6">
  			<dl class="dl-horizontal">
			  <dt>Created At </dt>
			  <dd> {{date('y-m-d',strtotime($role->created_at))}}</dd>
				<dt> Updated At</dt>
			  <dd>{{date('y-m-d',strtotime($role->updated_at))}}</dd>
				<dd></dd>
			  <dt>

	 		<dd>
	 		<dt><a href="{{ route('role.show', $role->id) }}" class="btn btn-primary" >Cancel</a></dt>

	 		<dt></dt>
	 		{!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
		 	</dd> 
			</dl>  
			
  {!! Form::close() !!}
  	</div>  
</div>
		
</div>
@endsection

resources/views/admin/roles/index.blade.php
@extends('layouts.app')
@section('content')


<Style>
	.role-heading {
		text-align: center;
	}
</style>
 <meta name="csrf-token" content="{{ csrf_token() }}" />
<div class="container">
@include('errors')
@if (session('role_created'))
    <div class="alert alert-success"> 
                  {{ Session::get('role_created')  }}  </div>
     {{ Session::forget('role_created') }}
                        
   @endif
 @if (session('role_deleted'))
    <div class="alert alert-success"> 
                  {{ Session::get('role_deleted')  }}  </div>
     {{ Session::forget('role_deleted') }}
                        
   @endif
    @if (session('role_updated'))
    <div class="alert alert-success"> 
                  {{ Session::get('role_updated')  }}  </div>
     {{ Session::forget('role_updated') }}
                        
   @endif

  <script type="text/javascript">
      
     $.ajaxSetup({  
         headers: {  
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')  
                      } 
                     });

  $(document).ready(function()
  {
     $('#datatableroles').dataTable();

    $('#getRequest').click(function()
    { 
     
        $('#reg').css('visibility', 'visible');
         
      $('#reg').show();
    });

     $('#cancel').click(function()
    { 
      $.get('cancel', function(data){
       
        $('#reg').css('visibility', 'hidden');
          });
      $('#reg').hide();
    });


    $('#submit').on('click',function()
    {
      var na=$('#name').val();
      var desc = $('#description').val();
      var token = $('input[name=_token]').val();
        if(na==''||desc=='')
        {
          $('#lab').text("REQUIRED");
         return false;
        
        }else if(na.length>50 || desc.length>50 )
        {
          $('#lab').text("Too much characters");
          return false;
        }
        else if(na.length<4 || desc.length<4 )
        {
          $('#lab').text("Too short");
          return false;
        }
        else if($.isNumeric(na) || $.isNumeric(desc))
        {
          $('#lab').text("Only characters allowed"); 
          return false;
        }
        else{  
          $('#register').submit();
      $.ajax({
          type: "POST", 
          url: "role", 
         beforeSend: function (xhr) {
            if (token) {
                  return xhr.setRequestHeader('X-CSRF-TOKEN', token);
            }
        },
          data:  {name: na, description: desc},
      success: function (result) {

                    window.location.reload('/role');
             
            }
      });
      }
    });
  });

  </script>
  <h2 class="role-heading"> Roles</h2>
    <table class="table" id="datatableroles">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Description</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      @foreach ($roles as $role)   
	           		<tr> 
                  <td>{{$role->id}} </td>
	           			<td> <i class="fa fa-users"></i> {{ ucfirst($role->name) }}</td>	
	           			<td> <i class="fa fa-info-circle"></i> {{ $role->description }}</td>                 
                  <td> <i class="fa fa-eye"></i> <a href="/role/{{$role->id}}" class="btn btn-info">View</a> </td>
                  @if($role->id == 1 || $role->id == 2)                 
                    
                    {!! Form::open(['method' => 'DELETE', 'route'=>['role.destroy', $role->id]]) !!}
                   <td>{!! Form::submit('Delete', ['class' => 'btn btn-danger', 'disabled']) !!}</td>
                   {!! Form::close() !!}
                 @else
                    <td>
                   <a href="#" style="color:inherit" onclick= "return confirm('Deleting this role will set ALL its users to clients.  CONTINUE ??');"> 
                    {!! Form::open(['method' => 'DELETE', 'route'=>['role.destroy', $role->id]]) !!}
                     {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                     {!! Form::close() !!}
                    </a>
                @endif             
          </td>          
	     </tr>

	        
			 @endforeach
    </tbody>
  </table>
<div class="container">
      
      <div class="row col-lg-5">
          <button type="button" class="btn btn-primary" id="getRequest">ADD NEW ROLE</button>
      </div>
    
      <div class="row col-lg-5" id="reg" style="visibility:hidden" >
     
        <h2>Register Role</h2>
        <form id="register" action="#">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
          <label  for="name">Role Name: </label>
          <input class="form-control" type="text" id="name">
          <label  id ="lab" for="length"></label><br>

          <label for="description">Role description: </label>
          <input class="form-control" type="text" id="description" style="margin-bottom : 15px;">
          
          <input type="submit" value="Add Role" class="btn btn-primary"  id="submit">
          <button type="reset" class="btn btn-primary" id="cancel">Cancel</button>
        </form>
     
      </div>
  </div>
</div>
@endsection		

resources/views/admin/roles/oldindex.blade.php
@extends('layouts.app')
@section('content')
 <meta name="csrf-token" content="{{ csrf_token() }}" />
<div class="container">
  <script type="text/javascript">
      
     $.ajaxSetup({  
         headers: {  
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')  
                      } 
                     });

  $(document).ready(function()
  {
     $('#datatableroles').dataTable();

    $('#getRequest').click(function()
    { 
      $.get('getRequest', function(data){
        
        $('#reg').css('visibility', 'visible');
          });
      $('#reg').show();
    });

     $('#cancel').click(function()
    { 
      $.get('cancel', function(data){
       
        $('#reg').css('visibility', 'hidden');
          });
      $('#reg').hide();
    });


    $('#submit').on('click',function()
    {
      var na=$('#name').val();
      var desc = $('#description').val();
      var token = $('input[name=_token]').val();
        if(na==''||desc=='')
        {
          $('#lab').text("REQUIRED");
         return false;
        
        }else if(na.length>50 || desc.length>50 )
        {
          $('#lab').text("Too much characters");
          return false;
        }
        else if(na.length<4 || desc.length<4 )
        {
          $('#lab').text("Too short");
          return false;
        }
        else if($.isNumeric(na) || $.isNumeric(desc))
        {
          $('#lab').text("Only characters allowed"); 
          return false;
        }
        else{  
          $('#register').submit();
      $.ajax({
          type: "POST", 
          url: "role", 
         beforeSend: function (xhr) {
            if (token) {
                  return xhr.setRequestHeader('X-CSRF-TOKEN', token);
            }
        },
          data:  {name: na, description: desc},//, '_token': token},
      success: function (result) {

          //setInterval(function() {
                    window.location.reload('/role');
                //}, 1000);
    }
      });
      /*
      $('#name').val() = '' ;
      $('#description').val() = '';
*/
      }
    });
  });

  </script>
  <h4>ROLES</h4>
    <table class="table" id="datatableroles">
    <thead>
      <tr>
        <th>Role</th>
        <th>Assigned to </th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      @foreach ($roles as $k)   
	           		<tr>          			
                  <div class="col-xs-2" >
                  {!! Form::model($k, ['method' => 'PUT', 'route' => ['role.update', $k->id] ] ) !!}

                @if($k->name=='admin' || $k->name =='client') 
                  <td> {!!Form::text('name', $k->name,['class' => 'form-control', 'disabled']) !!}
                  </td>
                @else
                  <td>  {!!Form::text('name', $k->name,['class' => 'form-control']) !!}</td>
               @endif
              
                  <td>{{ $k->users->count() }} users(s)</td>
	           			<td> {!!Form::text('description', $k->description,['class' => 'form-control']) !!}</td>

                  <td> {!! Form::submit('Update', ['class' => 'btn btn-default']) !!} </td>
                  {!! Form::close() !!}
                  
                  @if($k->name=='admin' || $k->name =='client') 
                  <td>  {!! Form::open(['method' => 'DELETE', 'route'=>['role.destroy', $k->id]]) !!}

                 {!! Form::submit('Delete', ['class' => 'btn btn-danger','disabled' => 'disabled']) !!}
                 {!! Form::close() !!}</td>
                 @else
                  <td>  {!! Form::open(['method' => 'DELETE', 'route'=>['role.destroy', $k->id]]) !!}

                 {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                 {!! Form::close() !!}</td>
                 @endif
                 </div>
	           		 </tr>
	        
			 @endforeach
    </tbody>
  </table>
   
</div>

	 <div class="container">
      
      <div class="row col-lg-5">
          <button type="button" class="btn btn-primary" id="getRequest">ADD NEW ROLE</button>
      </div>
    
      <div class="row col-lg-5" id="reg" style="visibility:hidden" >
     
        <h2>Register Role</h2>
        <form id="register" action="#">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
          <label  for="name">Role Name: </label>
          <input class="form-control" type="text" id="name">
          <label  id ="lab" for="length"></label><br>

          <label for="description">Role description: </label>
          <input class="form-control" type="text" id="description">
          
          <input type="submit" value="Add Role" class="btn btn-primary"  id="submit">
          <button type="reset" class="btn btn-primary" id="cancel">Cancel</button>
        </form>
     
      </div>
  </div>
 
@stop

resources/views/admin/roles/show.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
@include('errors')
<p class="lead">This is the role</p>
<div class="row ">
<div class="col-xs-6">
    <table class="table">
    <tbody>
	         <tr>
	  		<tr> 
	           <th>Name</th><td>{{$role->name}} </td>      			
	         </tr>
	         <tr> 
	           	<th>Description</th><td>{{$role->description}} </td>
	         </tr>
	         	<tr> 
	           	<th>Assigned to</th><td>{{ $role->users->count() }} user(s)</td>
	         </tr>      
    </tbody>
  </table>
  </div>
  	<div class="col-xs-6">
  		
  		<dl class="dl-horizontal">
			  <dt>Created At </dt>
			  <dd> {{date('y-m-d h:i:sa',strtotime($role->created_at))}}</dd>
				<dt> Updated At</dt>
			  <dd>{{date('y-m-d h:i:sa',strtotime($role->updated_at))}}</dd>
				<br>
			
			  <dt>
			  @if(!($role->id==1 || $role->id==2))
			  <a href="{{ route('role.edit', $role->id) }}" class="btn btn-info" >Update</a></dt>
			  @endif

			 <dd> <a href="{{ route('role.index') }}" class="btn btn-info" >Back</a></dd>
			</dl>  
  	</div>
			  
</div>

</div>
@endsection