app/Http/routes.php
<?php

use App\Image;
use Illuminate\Http\Request;
use App\Role;
use App\User;
use App\Category;
use App\Album;

Route::auth();

/******************************    ADMIN   ******************************************/
Route::group(['middleware' => ['AdminMiddleware', 'auth']], function()
{		
		Route::get('/admin', 'HomeController@index');
		
		Route::resource('user', 'UserController');
		Route::resource('role','RoleController');
    Route::resource('category', 'CategoryController');
    Route::resource('album', 'AlbumController');

    Route::put('/remove/{album}', 'CategoryController@removeAlbum');
    Route::put('/removeimg/{image}', 'AlbumController@removeImage');

    Route::get('roles/{role}', 'RoleController@show');
    Route::get('roles', 'RoleController@index');
		Route::get('user/create', 'UserController@create');
    Route::post('user/store', 'UserController@store');
    
    // Route::post('reset_password', 'UserController@test_fn');
    // Route::get('/reset_password', 'UserController@test_fn');
});

/*******************************   AUTH USER  *********************************************/
Route::group(['middleware' => 'auth'], function () {

  // CART BEGIN
  Route::get('/paypal_success', [
    'uses' => 'ImageController@successPayPal',
    'as' => 'Image.successPayPal'
  ]);
  Route::get('/checkout', [
    'uses' => 'ImageController@getCheckout',
    'as' => 'checkout',
  ]);
  Route::post('/checkout', [
    'uses' => 'ImageController@postCheckout',
    'as' => 'checkout',
  ]);
  Route::get('/shopping_cart\/', [
    'uses' => 'ImageController@getShoppingCart',
    'as' => 'image.getShoppingCart'
    ]
  );
  Route::get('/add_to_cart/{image}', [
      'uses' => 'ImageController@addImageToCart',
      'as' => 'image.addImageToCart'
    ]
  );
  Route::get('/decrease/{id}', [
    'uses' => 'ImageController@getDecreaseQty',
    'as' => 'image.decreaseQty'
  ]);
  Route::get('/increase/{id}', [
    'uses' => 'ImageController@getIncreaseQty',
    'as' => 'image.increaseQty'
  ]); 
  Route::get('/remove/{id}', [
    'uses' => 'ImageController@getRemoveImage',
    'as' => 'image.removeImage'
  ]);
  
  // CART END

  Route::get('/category','CategoryController@index');
  Route::get('/category/{category}','CategoryController@show');

  Route::get('/album','AlbumController@index');
  Route::get('/album/{album}','AlbumController@show');

  Route::get('/', 'CategoryController@index');
  // Route::get('/reset_password', 'UserController@change_password');

  Route::resource('image', 'ImageController');

  Route::get('/home', 'CategoryController@index');

  Route::post('user', 'UserController@store');
  Route::post('reset_password', 'PasswordResetController@reset_submit');
  Route::get('/reset_password', 'PasswordResetController@reset_password');
});

app/User.php
<?php
namespace App;
use App\User;
use Auth;
use Illuminate\Contracts\Auth\Authenticatable;
use Illuminate\Auth\Authenticatable as AuthenticableTrait;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends \Eloquent implements Authenticatable, CanResetPasswordContract
{
  use AuthenticableTrait, CanResetPassword;
  use SoftDeletes; 

	 public function role()
    {
        return $this->belongsTo('App\Role');
    }
    public function addImage(Image $image)
    {
      return $this->images()->save($image);
    }

    public function images()
    {
      return $this->hasMany('App\Image');
    }
    public function getRole()
    {
      return $this->role->id;
    }
  	public function assignRole(Role $role)
  	{
  		return $this->role()->save($role);
    }
    
    public function setDefault()
    {
      $r = Role::where('name','=','client')->get();
      return  $this->role()->assignRole($r);
    }

    public function hasImages()
    {
      return $this->images->count()>0;
    }

    public function isAdmin()
    {
        if ($this->role->name=='admin') {
          return true;
        }
        return false;
    }
    
    public function getLoggedInUser() 
    {
      return Auth::user();
    }

    public function orders()
    {
      return $this->hasMany('App\Order');
    }

    protected $dates = ['deleted_at'];
  
  	protected $fillable = ['username', 'email', 'password','newpassword_confirmation','newpassword'];

    protected $hidden = [
        'password', 'remember_token',
    ];
     protected $attributes = array(
        'role_id'  => 2,
    );

}

app/Http/Controllers/UserController.php
<?php
namespace App\Http\Controllers;
use App\User;
use App\Role;
use File;
use Session;
use Auth;
use Hash;
use Illuminate\Support\MessageBag;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Input;
use App\Http\Requests;

class UserController extends Controller
{    
    public function __construct()
    {
        $this->middleware('AdminMiddleware');
    }

    public function index()
    {
        //$users = User::withTrashed()->get();
        $users = User::all();
        return view('admin.users.index')->with('users', $users);
    }
    public function create()
    {
        $roles = Role::all();
        return view('admin.users.create')->with('roles', $roles);
    }
    public function store(Request $req)
    {
        $this->validate($req, [ 
            'username' =>  'required|regex:/^[\pL\s\-]+$/u|min:4|max:50|unique:users',   
            'email' => 'required|email|max:32|unique:users',
            'password' => 'required|min:7|confirmed',
        ]);

        $user =  new User([
            'username' => $req['username'],
            'email' => $req['email'],
            'password' => bcrypt($req['password']),
        ]);
        $get_role= $req['role_id'];
        $role = Role::where('id', '=', $get_role)->first();
        $role->addUser($user);
            
        Session::flash('user_created','User Added Successfully !');
        return redirect()->route('user.index');       
    }

    public function show(User $user)
    {
        return view('admin.users.show', compact('user'));
    }

    public function edit(User $user)
    {
        $arr = [
            'user' => $user,
            'roles' => Role::all()
        ];
        return view('admin.users.edit')->with('arr', $arr); 
    }
    
    public function update(Request $req,User $user)
    {
        $this->validate($req, [ 
            
            'role_id' => 'required'
        ]);         
        if($user->role->id == $req->role_id)
        {
        return redirect()->route('user.index');
        }
        else
        {

        $role_id = Role::where('id', '=', $req->role_id)->first();
        $user= User::find($user->id);
        $role_id->addUser($user);
        $user->save();
            
        Session::flash('user_updated', 'User Successfully Updated');
        return redirect()->route('user.index');
        }                
    }

    public function destroy(User $user)
    {
        $path = '/uploads/images/';
        
        if($user->hasImages())
        {
            foreach ($user->images as $image) {
                $p = $image->path;
            File::Delete(public_path($path.$image->path));
            $image->delete();
            }
        }

        $user->delete();
        Session::flash('user_deleted', 'User Successfully Deleted');
        return redirect()->route('user.index');
    }

    /************RESET PASSWORD************/
    public function reset_submit()
    {        
        var_dump("fjkldjfkldsjfldskjflkdsjflkds");
        $input = Input::except('_token');
        var_dump($input);
        $rules = array(
            'current_password' => 'required',
            'newpassword' => 'required|min:7|different:current_password|confirmed');

        $validator = Validator::make($input, $rules);

        if (!Hash::check($input['current_password'], Auth::user()->password)) 
        {               
            $validator->errors()->add('current_password', 'Current password wont match !');
            return back()->withErrors($validator);
        }
        else
        {
            if (!$validator->passes())
            {   
                return back()->withErrors($validator);
            }    
            else
            {
                Auth::user()->password = bcrypt($input['newpassword']); 
                Auth::user()->save();
                return redirect()->back()->with('pass_update', 'Password changed!');   
            }
        }
   
    }
    
    public function reset_password()
    {      
        return view('auth.reset_password');
    }

}

resources/views/admin/users/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">     
@include('errors')
              
          <center><h2>Create New User</h2></center>
          <p></p>
          
       {{ Form::open((array('url' => 'user/store', 'method' => 'post'))) }}
        {{ csrf_field() }}
            {!! Form::label('username','Username: ') !!}
             {!! Form::text('username',null,  array(
                                        'class'=> 'form-control'
                                        )) !!}
            {!! Form::label('email','Email Address: ') !!}
             {!! Form::text('email',null, array(
                                        'class'=> 'form-control'
                                        )) !!}                      
                     
              {!! Form::label('password','Password: ') !!}
             {!! Form::password('password',  array(
                                        'class'=> 'form-control'
                                        )) !!}
                                   
                 
              {!! Form::label('password_confirmation','Confirm Password: ') !!}
               
             {!! Form::password('password_confirmation',  array(
                                        'class'=> 'form-control'
                                        )) !!}  
                        
              <p></p>
              <p></p>
          {!! Form::label('role','Assign Role: ') !!}
            <select class="form-control" name="role_id">
       
                  @foreach($roles as $role)
            <option value = "{{ $role->id}}" {{   ($role->id ==2) ? 'selected = "selected" ': ''}} > {{ $role->name }} 
            </option>
                 
                  @endforeach 
            </select>
              <p></p>
              <p></p>

                                    <center>
               {!! Form::submit('Submit',array(
                                  'class'=> 'btn btn-primary'
                                        )) !!}  </center>
                       

         {!! Form::close() !!}



        </div>
    </div>
</div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
@include('errors')
<p class="lead">Edit User</p>
<div class="row ">
<div class="col-xs-6">
		
	{!! Form::model($arr['user'], [  'method' => 'PUT',  'route' => ['user.update', $arr['user']->id]]) !!}
	{{csrf_field() }}
 
    <table class="table">
    
	  		<tr> 
	          <th>Username</th><td>{!! Form::text('username', null, ['class' => 'form-control','disabled'] ) !!}</td>     		
	        </tr>
	         <tr> 
	         <th>E-mail Address</th><td>{!! Form::text('email', null, ['class' => 'form-control','disabled']) !!}</td> 	
	        </tr>
	        <tr><th>Assign Role </th>
	        <td>
            <select class="form-control" name="role_id">       
                  @foreach($arr['roles'] as $role)
		           
		          <option value = "{{ $role->id}}" {{   ($role->id == $arr['user']->role_id) ? 'selected = "selected" ': ''}} > {{ $role->name }} 
		            </option>
		            
                 
                  @endforeach 
            </select>
            </td>
            </tr>
	<!--         
	    	@foreach($arr['roles'] as $r)
				@if($r->id != $arr['user']->getRole())
				  <tr>
				  	<th></th>
				  	<td>{!!Form::radio('rolee', $r->name) !!}{{$r->name }}</td>				  
				  </tr>
				@else
				<tr>
				  <th></th>
				  <td>{!!Form::radio('rolee', $r->name ,'true')!!}{{$r->name}}</td>
				</tr>
				@endif
			@endforeach -->
   
  </table>
  </div>
  	<div class="col-xs-6">
  			<dl class="dl-horizontal">
			  <dt>Created At </dt>
			  <dd> {{date('y-m-d',strtotime($arr['user']->created_at))}}</dd>
				<dt> Updated At</dt>
			  <dd>{{date('y-m-d',strtotime($arr['user']->updated_at))}}</dd>
				<dd></dd>
			  <dt>
			  {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
			   <dd> <a href="{{ route('user.show', $arr['user']->id) }}" class="btn btn-primary" >Cancel</a></dd>
			  
			</dl>  
  	</div>  
</div>
		{!! Form::close() !!}

</div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')
@section('content')


<Style>
	.user-heading {
		text-align: center;
	}
</style> 
 <meta name="csrf-token" content="{{ csrf_token() }}" />
<div class="container">
@include('errors')
  @if (session('user_created'))
    <div class="alert alert-success"> 
                  {{ Session::get('user_created')  }}  </div>
     {{ Session::forget('user_created') }}
                        
   @endif
 @if (session('user_deleted'))
    <div class="alert alert-success"> 
                  {{ Session::get('user_deleted')  }}  </div>
     {{ Session::forget('user_deleted') }}
                        
   @endif
    @if (session('user_updated'))
    <div class="alert alert-success"> 
                  {{ Session::get('user_updated')  }}  </div>
     {{ Session::forget('user_updated') }}
                        
   @endif

 <script type="text/javascript">
    
    $('document').ready(function()
    {
      $('#datatableusers').dataTable();
    });
</script>
  <h2 class="user-heading"> All Registered Users</h2>
    <table class="table" id="datatableusers">
    <thead>
      <tr>
        <th>#</th>
        <th>Username</th>
        <th>Role</th>
        <th>View Users</th>
        <th>Delete Users</th>
      </tr>
    </thead>
    <tbody>
      @foreach ($users as $user)   
	           		<tr> 
                  <td>{{$user->id}} </td>
                  <!-- @if($user->trashed())               
                  @endif --> 
	           			<td> <i class="fa fa-user" aria-hidden="true"></i> {{ ucfirst($user->username) }}</td>	
	           			<td>  <i class="fa fa-hand-o-right" aria-hidden="true"> {{  $user->role->name }}</td>

                  <td> <i class="fa fa-eye" aria-hidden="true"></i> <a href="/user/{{$user->id}}" class="btn btn-info">View</a> </td>
                  @if(Auth::user()==$user) 
                   {!! Form::open(['method' => 'DELETE', 'route'=>['user.destroy', $user->id]]) !!} 
                  <td>         
                   {!! Form::submit('Delete', ['class' => 'btn btn-danger', 'disabled']) !!}
                   {!! Form::close() !!}
                   </a>
                </td>         
                  @else
                  <td>
                   <a href="#" style="color:inherit" onclick= "return confirm('Deleting this user will delete ALL its IMAGES .  CONTINUE ??');"> 
                      
              {!! Form::open(['method' => 'DELETE', 'route'=>['user.destroy', $user->id]]) !!}
             {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
             {!! Form::close() !!}
             </a>
          </td> 
             
          @endif  
	         </tr>
	        
			 @endforeach
    </tbody>
  </table>

  <a href="/user/create" class="btn btn-info" >ADD NEW USER</a>
</div>
@endsection		

resources/views/admin/users/messaged-success.blade.php
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

   @if (Session::has('category_created'))
                 
                 <div class="alert alert-success">
                   {{ Session::get('category_created')  }}  
                 </div>
                  {{ Session::forget('category_created')}}

  @endif
     @if (Session::has('category_updated'))
                 
                 <div class="alert alert-success">
                   {{ Session::get('category_updated')  }}  
                 </div>
                 

  @endif 
      @if (Session::has('category_deleted'))
                 
                 <div class="alert alert-success">
                   {{ Session::get('category_deleted')  }}  
                 </div>
  @endif 


@if (Session::has('deleted'))
                 
                 <div class="alert alert-success">
                   {{ Session::get('deleted')  }}  
                 </div>
               {{ Session::forget('deleted')}}

@endif 
  @if (Session::has('updated'))
                 
                 <div class="alert alert-success">
                   {{ Session::get('updated')  }}  
                 </div>

  @endif 
  @if (Session::has('success'))
                 
                 <div class="alert alert-success">
                   {{ Session::get('success')  }}  
                 </div>

  @endif 
   @if (Session::has('change_role'))
                 
                 <div class="alert alert-success">
                   {{ Session::get('change_role')  }}  
                 </div>
       
  @endif 
    @if (Session::has('deleted_role'))
                 
                 <div class="alert alert-success">
                   {{ Session::get('deleted_role')  }}  
                 </div>
       
  @endif 
   @if (Session::has('uploaded'))
                 
                 <div class="alert alert-success">
                   {{ Session::get('uploaded')  }}  
                 </div>

  @endif
  
   @if (Session::has('image_deleted'))
                 
                 <div class="alert alert-success">
                   {{ Session::get('image_deleted')  }}  
                 </div>

  @endif

   @if (Session::has('updated_name'))
                 
                 <div class="alert alert-success">
                   {{ Session::get('updated_name')  }}  
                 </div>

  @endif

   @if (Session::has('album_created'))
                 
                 <div class="alert alert-success">
                   {{ Session::get('album_created')  }}  
                 </div>

  @endif
  
   @if (Session::has('album_updated'))
                 
                 <div class="alert alert-success">
                   {{ Session::get('album_updated')  }}  
                 </div>

  @endif
   
    @if (Session::has('album_deleted'))
                 
                 <div class="alert alert-success">
                   {{ Session::get('album_deleted')  }}  
                 </div>

  @endif
  

    @if (Session::has('album_removed'))
                 
                 <div class="alert alert-success">
                   {{ Session::get('album_removed')  }}  
                 </div>

  @endif
   @if (Session::has('image_removed'))
                 
                 <div class="alert alert-success">
                   {{ Session::get('image_removed')  }}  
                 </div>

  @endif
    @if (Session::has('role_updated'))
                 
                 <div class="alert alert-success">
                   {{ Session::get('role_updated')  }}  
                 </div>

  @endif
  

@if (Session::has('no_albums'))
                 
                 <div class="alert alert-info">
                   {{ Session::get('no_albums')  }}  
                 </div>

  @endif
       @if (Session::has('no_images'))
                 
                 <div class="alert alert-info">
                   {{ Session::get('no_images')  }}  
                 </div>

  @endif

     @if (Session::has('no_albums_active'))
                 
                 <div class="alert alert-info">
                   {{ Session::get('no_albums_active')  }}  
                 </div>

  @endif  
  
       @if (Session::has('pass_update'))
                 
                 <div class="alert alert-success">
                   {{ Session::get('pass_update')  }}  
                 </div>

  @endif 
   
  

     @if (Session::has('updated_role'))
                 
                 <div class="alert alert-success">
                   {{ Session::get('updated_role')  }}  
                 </div>

  @endif 

resources/views/admin/users/show.blade.php
@extends('layouts.app')

@section('content')

<div class="container">

<p class="lead">This is the user</p>
<div class="row ">
<div class="col-xs-6">
    <table class="table">
    <tbody>
	         <tr>
	  		<tr> 
	           <th>Username</th><td>{{$user->username}} </td>      			
	         </tr>
	         <tr> 
	           	<th>E-mail Address</th><td>{{$user->email}} </td>
	         </tr>
	         	<tr> 
	           	<th>User Role</th><td>{{$user->role->name}} </td>
	         </tr>      
    </tbody>
  </table>
  </div>
  	<div class="col-xs-6">
  		
  		<dl class="dl-horizontal">
			  <dt>Created At </dt>
			  <dd> {{date('y-m-d h:i:sa',strtotime($user->created_at))}}</dd>
				<dt> Updated At</dt>
			  <dd>{{date('y-m-d h:i:sa',strtotime($user->updated_at))}}</dd>
				<br>
			
			  <dt>
			  @if(!($user->isAdmin() && Auth::user()==$user))

			  <a href="{{ route('user.edit', $user->id) }}" class="btn btn-info" >Update</a></dt>
			  @endif


			 <dd> <a href="{{ route('user.index') }}" class="btn btn-info" >Back</a></dd>
			</dl>  
  	</div>
			  
</div>

</div>
@endsection